org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

vecmath_version=1.5.2
joml_version=1.10.5

minecraft_version=1.21.1
neoforge_version=21.1.1-beta
neo_version=21.1.169
parchment_minecraft_version=1.21
parchment_mappings_version=2024.07.28
neo_version_range=[21.0.0-beta,)
mod_id=jurassicreborn
minecraft_version_range=[1.21,1.21.2)
loader_version_range=[4,)


geckolib_mc=1.21.1
geckolib_version=4.8.2

mc_version=1.21.1
jei_version=19.8.2.99

mod_name=Jurassic Reborn
# The license of the mod. Review your options at https://choosealicense.com/. All Rights Reserved is the default.
mod_license=All Rights Reserved (LGPL v2.1 applies to JurassiCraft-derived code only; see LICENSE)
# The mod version. See https://semver.org/
mod_version=1.3.43
# The group ID for the mod. It is only important when publishing as an artifact to a Maven repository.
# This should match the base package used for the mod sources.
# See https://maven.apache.org/guides/mini/guide-naming-conventions.html
mod_group_id=net.vit
# The authors of the mod. This is a simple text string that is used for display purposes in the mod list.
mod_authors=Vitiate
# The description of the mod. This is a simple multiline text string that is used for display purposes in the mod list.
mod_description=Jurassic Reborn is a complete prehistoric revival mod that brings dinosaurs, ancient creatures, and the world of paleontology to Minecraft. Discover fossils buried deep underground, extract DNA, and bring long-extinct creatures back to life using advanced machines and scientific processes. Build your own dinosaur park, manage ecosystems, and interact with 108 prehistoric species from towering sauropods to deadly raptors and marine giants. The mod also includes realistic animations, immersive sounds, ancient plants, and detailed gameplay systems inspired by both science and classic Jurassic lore. Whether you?re an explorer, a builder, or a paleontologist at heart, Jurassic Reborn lets you experience the ancient world like never before.

