org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

vecmath_version=1.5.2
joml_version=1.10.5

minecraft_version=1.19.4
forge_version=1.19.4-45.1.0

citadel_curse_id=331936
citadel_file_id=4634447
geckolib_mc=1.19.4
geckolib_version=4.2

mc_version=1.19.4
jei_version=13.1.0.11

parchment_version=2023.06.26-1.19.4
