modLoader="javafml"
loaderVersion="[35,)"
license="GNU Lesser General Public License v2.1"

[[mods]]
modId="rebornmod"
version="${file.jarVersion}"
displayName="RebornMod"
authors="Reborn Team"
description=""

[[dependencies.rebornmod]]
modId="forge"
mandatory=true
versionRange="[35,)"
ordering="NONE"
side="BOTH"

[[dependencies.rebornmod]]
modId="minecraft"
mandatory=true
versionRange="[1.16.4)"
ordering="NONE"
side="BOTH"